### ISSUE TITLE
rvizが頻繁に固まる

### ISSUE THREAD

**Issue by iou16** [open-rdc/orne_tools#3]
rvizが頻繁に固まる問題.
原因はvisualization_msgs::MarkerArray型のmarker_descriptionsという(waypointの番号などを配信している)トピックの配信されるレートが10Hzに設定されているからだった.
試しに1Hzにしたら, 問題が解消したため, そのように修正する.

**Comment by iou16** [comment]
問題なさそうなので勝手にmergeした.

**Comment by iou16** [comment]
やっぱり固まるようなので, 根本的な原因の解決には至っていなかったっぽい.原因究明する.

**Comment by iou16** [comment]
何も操作をしていなくても, メモリの消費量がガンガン増えているのは非常に怪しい.
![screenshot from 2017-02-24 14 21 09](https://cloud.githubusercontent.com/assets/7301090/23291529/978c4f94-fa9c-11e6-81b6-6b45d08437fc.png)

**Comment by DaikiMaekawa** [comment]
たまたま目に入ったからコメントするけど、プロセス単体でのメモリの使用量は確認した?

**Comment by iou16** [comment]
プロセス単体では確認していませんが, このプロセスを殺すとメモリ消費量が一気に下がるので, おそらくこれが原因かと. それらしき実装ミスも発見しています.

**Comment by DaikiMaekawa** [comment]
次回からで良いですけど、対象を絞り込んだ上で作業を始めると時間が節約できる事も多いですよ。 `top`コマンド等でも簡単に調べるだけなら十分役に立ちます。
